### ISSUE TITLE
ValueError: Namespace GSystem not available

### ISSUE THREAD

**Issue by miabbott** [projectatomic/rpm-ostree-toolbox#104]
Using an updated F25 system, trying to run `rpm-ostree-toolbox` fails with the above error.

```
# rpm-ostree-toolbox --help
Traceback (most recent call last):
  File "/usr/lib64/rpm-ostree-toolbox/py/rpmostreecompose-main", line 23, in <module>
    from rpmostreecompose import taskrunner, version, liveimage, docker_image
  File "/usr/lib64/rpm-ostree-toolbox/py/rpmostreecompose/taskrunner.py", line 28, in <module>
    gi.require_version('GSystem', '1.0')
  File "/usr/lib64/python2.7/site-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GSystem not available
# rpm -q ostree pygobject2 rpm-ostree rpm-ostree-toolbox
ostree-2016.13-2.fc25.x86_64
pygobject2-2.28.6-16.fc25.x86_64
rpm-ostree-2016.12-2.fc25.x86_64
rpm-ostree-toolbox-2016.1-1.fc25.x86_64
```

This was originally reported on #atomic by @wickedviking

**Comment by wickedviking** [comment]
I can provide logs and stuff, just let me know what you need.

**Comment by cgwalters** [comment]
This is http://pkgs.fedoraproject.org/cgit/rpms/rpm-ostree-toolbox.git/commit/?id=981b50c50a8fa4a1574f014b127a768f4a31d16a

For now just `yum/dnf/rpm-ostree install libgsystem`.

**Comment by wickedviking** [comment]
after installing libgsystem I get:

rpm-ostree-toolbox --help
  File "/usr/lib64/rpm-ostree-toolbox/py/rpmostreecompose-main", line 48
    print "\nrpm-ostee-toolbox requires you to run as root"

**Comment by miabbott** [comment]
@wickedviking Strange, I did not see that.  I'd file a separate issue.

```
# dnf install libgsystem
Last metadata expiration check: 1:33:40 ago on Fri Dec  2 17:06:19 2016.
Dependencies resolved.
===================================================================================================================================================================================================================
 Package                                             Arch                                            Version                                                 Repository                                       Size
===================================================================================================================================================================================================================
Installing:
 libgsystem                                          x86_64                                          2015.2-2.fc24                                           fedora                                           49 k

Transaction Summary
===================================================================================================================================================================================================================
Install  1 Package

Total download size: 49 k
Installed size: 112 k
Is this ok [y/N]: y
Downloading Packages:
libgsystem-2015.2-2.fc24.x86_64.rpm                                                                                                                                                142 kB/s |  49 kB     00:00    
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                               48 kB/s |  49 kB     00:01     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Installing  : libgsystem-2015.2-2.fc24.x86_64                                                                                                                                                                1/1 
  Verifying   : libgsystem-2015.2-2.fc24.x86_64                                                                                                                                                                1/1 

Installed:
  libgsystem.x86_64 2015.2-2.fc24                                                                                                                                                                                  

Complete!
# rpm-ostree-toolbox --help
Builtins:
  treecompose - Use rpm-ostree to compose RPMs to a tree
  imagefactory - Use ImageFactory to create a disk image
  installer - Use Lorax to create an installable ISO and PXE boot loader
  liveimage - Use Imagefactory and Live Media Creator to create live media
  docker-image - Generate a base Docker image
  create-vm-disk - Deprecated in favor of imagefactory
  postprocess-disk - Deprecated; instead use imagefactory to generate multiple images
```
